change \n to echo

diff --git a/setup-my-pc b/setup-my-pc
--- a/setup-my-pc
+++ b/setup-my-pc
@@ -16,41 +16,62 @@ programLists=(
 	'tree'
 )
 
-su -c apt-get install ${programList[@]} || (echo 'Error installing programs' && exit 2)
+apt-get install ${programLists[@]} || (echo 'Error installing programs'; exit 2)
 
 
 #
 # Installing programs with different setup steps
 # 1. Meteor
+echo
+echo
+echo "Installing Meteor..."
 if hash meteor 2>/dev/null; then
+	echo "Meteor already installed. Skipping..." 
 else
-	curl https://install.meteor.com/ | sh
+	(curl https://install.meteor.com/ | sh) || (echo "Error: Couldn't install meteor. Skipping...\nYou can install later by running \n\n\t curl https://install.meteor.com/ | sh"; exit 3);
 fi
 
+echo
+echo
+echo "Installing Ruby via rvm..."
 # 2. Ruby and Rails
 if hash rvm 2>/dev/null; then
+	echo "Ruby Version Manager (RVM) already installed. Skipping..."
 else
-	curl -sSL https://get.rvm.io | bash -s stable --ruby
-if
+	(\curl -sSL https://get.rvm.io | bash -s stable --ruby) || (echo "Error: Couldn't install rvm. Skipping...\nYou can later install by typing \n\n\t curl -sSL https://get.rvm.io | bash -stable --ruby"; exit 4)
+fi
 
 # check if rails is installed else install it
+echo
+echo
+echo "Installing Rails..."
 if hash rails 2>/dev/null; then
+	echo "Rails already installed. Skipping..."
 else
-	gem install rails
+	gem install rails || (echo "Error: Couldn't install rails. Skipping...\nVerify that you have rvm installed and run\n\n\tgem install rails"; exit)
+fi
 
 #
 # Terminal Configuration
 # - Git configuration
+echo
+echo
+echo "Configuring Git..."
 git config --global user.name "Samuel Nkoom Amoah"
 git config --global user.email snamoah@gmail.com
 
+echo "Installing git flow..."
+apt-get install git-flow
 #
 # Aliases
 # (Read content from aliases file and append into .bashrc file in /home directory
 #
 #
+
+echo
+echo
+echo "Setting up aliases..."
 cat aliases >> ~/.bashrc
-exec bash
 
 
 #
@@ -58,5 +79,20 @@ exec bash
 #
 # First verify if ~/.vim/bundle folder exists else create it
 #
+echo
+echo
+echo "Configuring vim editor..."
 cat vim-plugins >> ~/.vimrc
+
+# Editor config and tpope/fugitive conflict fixes
+echo "let g:EditorConfig_exclude_patterns = ['fugitive://.*']" >> ~/.vimrc
+
 vim +PluginInstall +qall # install plugins 
+
+echo 
+echo
+echo "*********************** Done!!!! ****************************"
+echo
+
+# Reset bash so bash profile configuration can start working immediately
+exec bash
